import os
import csv

header_2010 = '"DATA_GERACAO";"HORA_GERACAO";"ANO_ELEICAO";"NUM_TURNO";"DESCRICAO_ELEICAO";"SIGLA_UF";"SIGLA_UE";"DESCRICAO_UE";"CODIGO_CARGO";"DESCRICAO_CARGO";"NOME_CANDIDATO";"SEQUENCIAL_CANDIDATO";"NUMERO_CANDIDATO";"CPF_CANDIDATO";"NOME_URNA_CANDIDATO";"COD_SITUACAO_CANDIDATURA";"DES_SITUACAO_CANDIDATURA";"NUMERO_PARTIDO";"SIGLA_PARTIDO";"NOME_PARTIDO";"CODIGO_LEGENDA";"SIGLA_LEGENDA";"COMPOSICAO_LEGENDA";"NOME_LEGENDA";"CODIGO_OCUPACAO";"DESCRICAO_OCUPACAO";"DATA_NASCIMENTO";"NUM_TITULO_ELEITORAL_CANDIDATO";"IDADE_DATA_ELEICAO";"CODIGO_SEXO";"DESCRICAO_SEXO";"COD_GRAU_INSTRUCAO";"DESCRICAO_GRAU_INSTRUCAO";"CODIGO_ESTADO_CIVIL";"DESCRICAO_ESTADO_CIVIL";"CODIGO_NACIONALIDADE";"DESCRICAO_NACIONALIDADE";"SIGLA_UF_NASCIMENTO";"CODIGO_MUNICIPIO_NASCIMENTO";"NOME_MUNICIPIO_NASCIMENTO";"DESPESA_MAX_CAMPANHA";"COD_SIT_TOT_TURNO";"DESC_SIT_TOT_TURNO"\n'
header_2012 = '"DATA_GERACAO";"HORA_GERACAO";"ANO_ELEICAO";"NUM_TURNO";"DESCRICAO_ELEICAO";"SIGLA_UF";"SIGLA_UE";"DESCRICAO_UE";"CODIGO_CARGO";"DESCRICAO_CARGO";"NOME_CANDIDATO";"SEQUENCIAL_CANDIDATO";"NUMERO_CANDIDATO";"CPF_CANDIDATO";"NOME_URNA_CANDIDATO";"COD_SITUACAO_CANDIDATURA";"DES_SITUACAO_CANDIDATURA";"NUMERO_PARTIDO";"SIGLA_PARTIDO";"NOME_PARTIDO";"CODIGO_LEGENDA";"SIGLA_LEGENDA";"COMPOSICAO_LEGENDA";"NOME_LEGENDA";"CODIGO_OCUPACAO";"DESCRICAO_OCUPACAO";"DATA_NASCIMENTO";"NUM_TITULO_ELEITORAL_CANDIDATO";"IDADE_DATA_ELEICAO";"CODIGO_SEXO";"DESCRICAO_SEXO";"COD_GRAU_INSTRUCAO";"DESCRICAO_GRAU_INSTRUCAO";"CODIGO_ESTADO_CIVIL";"DESCRICAO_ESTADO_CIVIL";"CODIGO_NACIONALIDADE";"DESCRICAO_NACIONALIDADE";"SIGLA_UF_NASCIMENTO";"CODIGO_MUNICIPIO_NASCIMENTO";"NOME_MUNICIPIO_NASCIMENTO";"DESPESA_MAX_CAMPANHA";"COD_SIT_TOT_TURNO";"DESC_SIT_TOT_TURNO";"NM_EMAIL"\n'
header_2014 = '"DATA_GERACAO";"HORA_GERACAO";"ANO_ELEICAO";"NUM_TURNO";"DESCRICAO_ELEICAO";"SIGLA_UF";"SIGLA_UE";"DESCRICAO_UE";"CODIGO_CARGO";"DESCRICAO_CARGO";"NOME_CANDIDATO";"SEQUENCIAL_CANDIDATO";"NUMERO_CANDIDATO";"CPF_CANDIDATO";"NOME_URNA_CANDIDATO";"COD_SITUACAO_CANDIDATURA";"DES_SITUACAO_CANDIDATURA";"NUMERO_PARTIDO";"SIGLA_PARTIDO";"NOME_PARTIDO";"CODIGO_LEGENDA";"SIGLA_LEGENDA";"COMPOSICAO_LEGENDA";"NOME_LEGENDA";"CODIGO_OCUPACAO";"DESCRICAO_OCUPACAO";"DATA_NASCIMENTO";"NUM_TITULO_ELEITORAL_CANDIDATO";"IDADE_DATA_ELEICAO";"CODIGO_SEXO";"DESCRICAO_SEXO";"COD_GRAU_INSTRUCAO";"DESCRICAO_GRAU_INSTRUCAO";"CODIGO_ESTADO_CIVIL";"DESCRICAO_ESTADO_CIVIL";"CODIGO_COR_RACA";"DESCRICAO_COR_RACA";"CODIGO_NACIONALIDADE";"DESCRICAO_NACIONALIDADE";"SIGLA_UF_NASCIMENTO";"CODIGO_MUNICIPIO_NASCIMENTO";"NOME_MUNICIPIO_NASCIMENTO";"DESPESA_MAX_CAMPANHA";"COD_SIT_TOT_TURNO";"DESC_SIT_TOT_TURNO";"NM_EMAIL"\n'

files = os.listdir("base")
f_2010 = open("cand_2010.csv", "w")
# f_2012 = open("cand_2012.csv", "w")
# f_2014 = open("cand_2014.csv", "w")
f_2010.write(header_2010)
# f_2012.write(header_2012)
# f_2014.write(header_2014)

for filename in filter(lambda a: "consulta_cand" in a, files):
    index = len("consulta_cand_")
    ano = int(filename[index:index+4])
    f = open("base/" + filename)
    if ano == 2012:
        pass
        # f_2012.write(f.read())
    elif ano < 2012:
        f_2010.write(f.read())
    else:
        pass
        # f_2014.write(f.read())

f_2010.close()
# f_2012.close()
# f_2014.close()

